name = "PackageURL"
uuid = "c2271b70-7219-4bda-bcc3-62ec08ead5b7"
version = "0.4.0"
authors = ["PackageURL.jl Contributors"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
JSON3 = "1"
Pkg = "1.6"
UUIDs = "1.6"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JSONSchema"]
